# -*- coding: utf-8 -*-
"""transformer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y9TKM90WJOzE1OB2s4jf5EhG_ZDbWfoQ
"""

# transformer.py
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import pandas as pd

def cluster_riders(df: pd.DataFrame, n_clusters: int = 5) -> pd.DataFrame:
    features = ['frequency_count', 'total_trips', 'avg_trips_per_day']
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(df[features])

    model = KMeans(n_clusters=n_clusters, random_state=42)
    df['cluster'] = model.fit_predict(X_scaled)

    return df

def summarize_clusters(df: pd.DataFrame) -> str:
    return df['cluster'].value_counts().to_string()